import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>nueLIVING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl">nueLIVING</h1>
    </div>
  );
}
